### ISSUE TITLE
Fan Speed slider not in sync with Moodo App and HomeKit

### ISSUE THREAD

**Issue by DJay-X** [moodoapplication/homebridge-moodo#1]
As probably already mentioned earlier somewhere, thanks for this great plugin. 😉
Configuration, thanks to https://homebridge.moodo.co/#/login ,was so easy and the plugin runs stable.

Just to point to it and nothing critical, I noticed that the speed of fan slider of Moodo App and HomeKit App, like Apple Home or Elgato Eve App, is not in sync. See example in the video.
Maybe it's something for one of the next updates. No hurry. 
https://youtu.be/cqdIYEjXh28

Also a [release note](https://github.com/moodoapplication/homebridge-moodo/releases) would be great so that people know what to expect when updating. Or even better to put a CHANGELOG.md to the Project so that it shows up in [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) after updating. 

Thanks again for your great work and the time you are investing. ❤️👍🏻

**Comment by moodoapplication** [comment]
Dear DJay-X,

Thanks for your support! I appreciate it very much! :)
Just added a first release note and a CHANGELOG.md file. Can you please check if it's ok?

You are right, there is no heartbeat support service for the homebridge plugin yet.
It will be done really soon :D

Happy holidays!

**Comment by DJay-X** [comment]
Change Log, looks and works great to me. 👍  Thanks for your ongoing work.
If you ever come to Frankfurt/M., DE, say Hi and you get a beer. :)

![bildschirmfoto 2018-12-14 um 18 23 42](https://user-images.githubusercontent.com/3874239/50017902-d616d800-ffcd-11e8-9dd9-57e97d4e747d.png)
![bildschirmfoto 2018-12-14 um 18 24 17](https://user-images.githubusercontent.com/3874239/50017906-d911c880-ffcd-11e8-8f0c-d515ed03a7fb.png)

**Comment by moodoapplication** [comment]
Dear DJay-X,

It's done :D

Happy Christmas,
Vladi
