### ISSUE TITLE
Changelog in config-ui-x

### ISSUE THREAD

**Issue by DJay-X** [moodoapplication/homebridge-moodo#10]
Thanks @lukasroegner for the previous updates.
I noticed that when updating with config-ui-x at the beginning the change log is showing up from https://github.com/moodoapplication/homebridge-moodo/releases
![Bildschirmfoto 2020-04-12 um 12 00 07](https://user-images.githubusercontent.com/3874239/79066153-d99b9b80-7cb5-11ea-9064-75c4a95dccac.png)

When the update is finished it is showing the actual up-to-date changes from 
https://github.com/moodoapplication/homebridge-moodo/blob/master/CHANGELOG.md
![Bildschirmfoto 2020-04-12 um 12 00 47](https://user-images.githubusercontent.com/3874239/79066159-f0da8900-7cb5-11ea-8ed9-0f50ac6f19ad.png)

You probably just want "one" up-to-date showing up before starting the update. Or the same at start and end of the update.

Thanks and of course relaxing 🐰🐣😉

**Comment by lukasroegner** [comment]
I'll try to remember adding releases for new versions.
