### ISSUE TITLE
Error display for unreachable moodo

### ISSUE THREAD

**Issue by Nastras** [moodoapplication/homebridge-moodo#12]
I just noticed that if a moodo is not reachable there is a node error in the log in addition to the normal message of the plugin. This did not affect the plugin directly. But I seem to remember that if this error occurs too often the node freezes the plugin at some point. I already had it with another plugin.

![B6141034-7962-43D9-BB52-43A63E411505](https://user-images.githubusercontent.com/27686185/79067850-bfb48580-7cc2-11ea-9649-d5373f696951.jpeg)

**Comment by lukasroegner** [comment]
Can you try `npm install -g homebridge-moodo@next` ? This beta version should show the warnings, however, it should not create `UnhandledPromiseRejectionWarning`s.

**Comment by Nastras** [comment]
Bug is fixed 👍👍👍
