### ISSUE TITLE
[Question/Enhancement] Timer default duration time is set to 0 after restart

### ISSUE THREAD

**Issue by DJay-X** [moodoapplication/homebridge-moodo#13]
Hi @lukasroegner 
Because of the nature of my hobby I have to restart Homebridge a couple of times.
I noticed that the Moodo Timer setting looks like to be always reset to 0 after rebooting homebridge. Is this intended to be? Otherwise the last set time to keep would be great.

As always, thanks a lot.

![Napkin 18 04 20, 4 16 31 PM](https://user-images.githubusercontent.com/3874239/79640102-fccfba80-818f-11ea-8e92-fc5d5da0a959.png)

**Comment by lukasroegner** [comment]
Hi @DJay-X,

Are you sure that there is no automation that sets the timer duration? The duration property should be cached by homebridge as any other characteristic.

I did the following test:
- Set duration via Eve app to 2 minutes
- Wait 10 seconds
- Close eve app
- Stop homebridge
- Wait 10 seconds
- Start homebridge
- Wait 20 seconds
- Open Eve app
- Now, the duration still shows 2 minutes.

Does the plugin behave differently if you execute the same test?

**Comment by DJay-X** [comment]
Hmm... I could have sworn it is going back to 0 after reboot. 
But... it's not after testing. 😅🤷🏼‍♂️
I always set it to 30 min and the past days I was wondering why it stopped immediate after start. Checking the App and it was on 0. Strange thing.
I'll have an eye on it. 👀 Maybe it's a strange automation I have set up. 

I close this issue for now and reopen it when I get back feeling more confident. 😬

Anyway, sorry and thanks @lukasroegner
