### ISSUE TITLE
Feature request: user settings

### ISSUE THREAD

**Issue by Donni1966** [moodoapplication/homebridge-moodo#14]
First: i love this device and we still use it every day. 

So,  my wife combine very often scenarios wir light and a combination on setting on the Moodo. 

what we look  for is an option to call the preset user Config (behind the heart) to send this with an scenario to moodo over the plugin. 

I know it is possible to do this separate with the fans, but steh HomeKit is my domain the moodo config semself the job of her.

**Comment by lukasroegner** [comment]
Hi @Donni1966,

Unfortunately, it is not possible to create HomeKit scenes from Moodo favorites with homebridge.

As you already mentioned, the solution would be to set `showCapsules` to `true` and configure the fans for the capsules in the HomeKit scene.
