### ISSUE TITLE
Unable to config properly HOOBS3

### ISSUE THREAD

**Issue by Rick-Mar** [moodoapplication/homebridge-moodo#17]
Hi all,

Im fairly new to this and trying to get moodo set up on HOOBS. 
The config page only asks for the token and the number of the device. 
I entered that but when booting the log gives the following error: 

23-1-2021 16:32:02 [MoodoPlatform] Initialing platform...
23-1-2021 16:32:02 [MoodoPlatform] Device ID or name missing in the configuration.

If I include the name in the device id it refuses to save. the current config looks like this: 

 {
            "platform": "MoodoPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-moodo"
            },
            "devices": [
                315
            ],
            "token": "My Token"
        }

This is not like its set in the Readme here. If tried to set this part of the config like stated here but am unable to save cause HOOBS states its no longer a valid JSON.

Edit: this is the config UI from HOOBS

<img width="1144" alt="Schermafbeelding 2021-01-23 om 17 07 57" src="https://user-images.githubusercontent.com/77890815/105607218-dc2b3580-5d9d-11eb-8cd2-b26dba5bb01f.png">

Thanks in advance for any help. 
Rick

**Comment by lukasroegner** [comment]
Please take a look at the README. The devices array is not just an array of device IDs, it is an array of object in which the ID is provided in the property `id`.

**Comment by Rick-Mar** [comment]
I indeed missed a thing. this is wat the auto setup spit out. Filled it out and got it working. 

Thanks.
