### ISSUE TITLE
Display charge indicators in homekit

### ISSUE THREAD

**Issue by Nastras** [moodoapplication/homebridge-moodo#2]
Hello, first of all a praise for the great product and the super easy integration into homekit.

Would it be possible for you to display the charge indicator in homekit for the Moodo with battery? That would be a great extension.

Greeting Nastras

**Comment by moodoapplication** [comment]
Dear Nastras,

Thank you so much for your feedback!

Unfortunately current Moodo devices do not have indication of battery level, so it's not possible for the moment, but we are looking forward to support this and other features in near future. :)

Please subscribe to our newsletter at https://moodo.co and stay tuned to our news.
I am sure everyone who loves Moodo today will love it much more in the upcoming 2020.

Have a great New Year!
Moodo Team

**Comment by Nastras** [comment]
Thanks for the answer. Too bad it's not possible.

I am curious what you have to offer in 2020 😉
