### ISSUE TITLE
Slider or Switches for different scent scenes

### ISSUE THREAD

**Issue by Nastras** [moodoapplication/homebridge-moodo#3]
I have idea how you can extend the plugin with a very helpful function.

Can you build in a slider that has for example 6 steps.

These 6 levels could be assigned to certain scent scenes via the config.json.

This way you could also change the scent scenes in HK.

Alternatively it would be possible to add additional switches that are all displayed under a moodo device in homekit to select different scent scenes.

I hope you like the idea?

Best Regards

Nastras

**Comment by moodoapplication** [comment]
Hey Nastras,

Thank you so much for your feedback and idea!

As far as i know, Homebridge (and/or HomeKit) supports only limited number of device profiles.
I wasn't able to create a device with more than 1 switch and slider in the Homebridge, but use very simple one with switch and fan.

For example, in SmartThings, which has published an integration with Moodo recently, i've created a custom device, using their developers portal with slider for each fan and if i wanted, also a switch, but their interface wasn't convenient for 4 additional switches, each of half mobile screen.

If you would help us with code or point to some documentation where we would achieve the functionality you are asking, we would definitely go forward and do it ASAP.

Thanks and have a great year!
Vladi

**Comment by Nastras** [comment]
I am glad to hear that you are interested in further developing the plugin.

Look here at the plugin [homebridge-tado-platfor](https://github.com/SeydX/homebridge-tado-platform)m here the developer has added several sliders and additional switches on one device / thermostat. I hope you can orientate yourself by the code.

Here is a picture how it looks like in HomeKit in a third party app:

![D20F7FE4-050D-458F-A315-3967922F90B0](https://user-images.githubusercontent.com/27686185/71684389-a92e9200-2d95-11ea-8bbd-49de15c3f42c.png)


Best Regards

Nastras

**Comment by Nastras** [comment]
Hello, I wanted to ask if this tip is helpful?

**Comment by Nastras** [comment]
Hello everyone, I'm a little disappointed that the Moodo team is no longer reacting. Although your device has so much potential.

You were talking about ASAP upstairs and nothing is happening.

Well, I've given it some more thought and the idea of the slider from above might not be the best.
You could use a custom charistics switch instead of a slider to select your favorites. 

Here you could say per Moodo you can use the Config to set your 4 favorites which will then be shown as custom charistics switch in the homekit under the moodo fan. The moodo API already offers this function.

It would also be nice if you could add a turn off delay slider like the homebridge-cmdtriggerswitch​ plugin (Interactive Delay Switch) to control the duration. 
https://github.com/hans-1/homebridge-cmdtriggerswitch

By extending the two functions an almost complete control of the moodo via homekit would be possible.

So i hope dear moodo team that you are interested in expanding your plugin to give homekit users a better user experience.

**Comment by moodoapplication** [comment]
Hey Nastras,

Thanks for your feedback and sorry for your wait. 
We were very busy in Vegas at CES 2020 a month ago and currently trying to contact back all the people excited about Moodo.

Could I ask you please to send a short mail to support@moodo.co and we'll be in touch there much closer.

I am closing this thread and want to thank you again for your exceptional patience and cooperation!
