### ISSUE TITLE
Cannot install via Homebridge-UI-X Console

### ISSUE THREAD

**Issue by clipse2004** [moodoapplication/homebridge-moodo#4]
Hey dude,

I want your plugin version 2 but I cannot install it via Config-UI-X Console. I only fund the older one.
Why?

Thanks!

**Comment by lukasroegner** [comment]
HI @clipse2004,

The version 2 is currently in "beta", you can install it via command line:
```
npm install -g homebridge-moodo@next
```

**Comment by clipse2004** [comment]
Hi Lukas ich glaub du kannst deutsch oder? :)
Mein Problem ist das ich Hoobs laufen habe, da ist das nicht ganz so einfach machbar.
Wenn ich das so installiere, dann taucht das bei hoobs gar nicht auf.
Und wenn ich das über das alte Plugin drüber installiere erscheint das neue zwar, aber der ordnet es den accecorys zu und nicht unter Platform :/

**Comment by lukasroegner** [comment]
Hi @clipse2004, indeed I speak German, but I highly recommend writing in English on GitHub, as other people with the same/similar issue might also be interested in the solution ;)

The new version is currently in "beta", which means you cannot install it via Hoobs or Config UI.
We plan to release the new version on Saturday or Sunday, so stay tuned!

Hint: the new version uses the dynamic platform accessory feature of Homebridge, so (as you might have already seen in the README on the `next` branch) the config of the plugin changes.

**Comment by lukasroegner** [comment]
Dear @clipse2004, the new version is now published, which means you can install it via Hoobs.
If you have any issues, feel free to submit an issue!

**Comment by clipse2004** [comment]
Mmh when you search under npm for Homebridge-moodo it only shows 1.2.2. but when I click on it, then is 2.0.3 there :/

**Comment by lukasroegner** [comment]
I assume NPM is using a search index for the search. As with all search indexes, it might need some time for the search index to get updated.

**Comment by clipse2004** [comment]
ok no problem but after installation i got this error:
[Homebridge] [4/8/2020, 5:54:35 AM] TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:31:14)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:258:48)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

i added the new config from your readme, but when i click on "Add Device" in Hoobs it always give automatical this:
{
    "accessory": "HomebridgeMoodo"
}

after replace with "platform" i got the error

**Comment by lukasroegner** [comment]
It seems that there is a caching issue, maybe Hoobs caches plugins???

I would suggest to:
- Completely uninstall the plugin from Hoobs
- Restart Hoobs, check if everything is running
- Install the plugin again (can you specify anything other than the plugin name in Hoobs)?
- Configure the plugin via UI (is supported in the new version)

**Comment by clipse2004** [comment]
nope doesnt show up. lets wait a bit

**Comment by clipse2004** [comment]
Yep now I can install it :) thanks!
