### ISSUE TITLE
Setting leftover "showCapsules"

### ISSUE THREAD

**Issue by DJay-X** [moodoapplication/homebridge-moodo#6]
@lukasroegner 
I installed the plugin with the settings "showCapsules": false,.
Then for testing purpose I set "showCapsules": true, and "useCapsuleNames": tue,

Now back to the "default" false, in HomeKit the capsules still showing up, but strange. 2x Moodo, 2x Capsule. There should be non at all with this setting I think?

I already deletes "cached accessories" but the four switches still showing up.

Thanks for you help.

```
{
            "platform": "MoodoPlatform",
            "token": "xxxx",
            "devices": [
                {
                    "id": xxxx,
                    "name": "Moodo",
                    "type": "purifier",
                    "showCapsules": false,
                    "useCapsuleNames": false,
                    "isSingleAccessoryModeEnabled": true
                }
            ]
        },
```

![Napkin 09 04 20, 1 37 00 PM](https://user-images.githubusercontent.com/3874239/78891137-35bcb080-7a67-11ea-8b51-7db3aea35776.png)

**Comment by lukasroegner** [comment]
Hi @DJay-X,

I'll check if there is an issue in the implementation. If you want a quick fix: temporary remove the device from the config.json (i.e. `"devices": []`), restart homebridge, add the device again with correct settings, restart homebridge.

**Comment by lukasroegner** [comment]
Dear @DJay-X,

Thank you so much for reporting this issue, it is solved now!
