### ISSUE TITLE
Race condition with socket.io

### ISSUE THREAD

**Issue by moodoapplication** [moodoapplication/homebridge-moodo#7]
Dear Lukas,

Please use "restful_request_id" optional parameter as unique string for each request, so you could ignore socket.io pushes with same value (triggered from the same device)

Thanks a lot!

**Comment by lukasroegner** [comment]
New update is on master and NPM, where the parameter is used. Moreover, I also enhanced the logic when switch the device on/off and changing rotation speed, so that jumping sliders should no longer occur.
