### ISSUE TITLE
Feature Request: Delay Timer

### ISSUE THREAD

**Issue by Nastras** [moodoapplication/homebridge-moodo#9]
Hi Lukas, would it be possible for you to install a delay timer that can be set in HK with a slider in min on the device and allows you to switch off Moodo after a certain time?

Thank you!

Best regards
Nastra

**Comment by lukasroegner** [comment]
Implemented in the latest version 2.1.0. I used an existing characteristic for the duration instead of a custom one, so that there is a higher chance that third-party apps support the characteristic. I tested it in the Eve app, which shows a nice timer symbol and duration selection.

**Comment by Nastras** [comment]
Hello, yes the timer works great. Thank you very much for the quick implementation 👌
